spring.application.name=DnD-Tool
server.port=8081
# MySQL-Verbindung
spring.datasource.url=jdbc:mysql://localhost:3306/dnd_2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=DnD_Tool
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# jwt.secret=${JWT_SECRET}
# jwt.expiration=${JWT_EXPIRATION}

# Lokale Entwicklung ? feste Werte statt Umgebungsvariablen
jwt.secret=dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5Zm9ySldUdXNhZ2UxMjM0NTY3ODk=
jwt.expiration=86400000